version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: concert-ticketing-api
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/test_db?characterEncoding=UTF-8
      DB_USERNAME: test_user
      DB_PASSWORD: test_password
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - concert-ticketing-network
  mysqldb:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: mysql:8.0
    container_name: concert-ticketing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    networks:
      - concert-ticketing-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/mysql/my.cnf
networks:
  concert-ticketing-network:
