spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/test_db}
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8083}

jwt:
  access_token_secret_key: ${ACCESS_TOKEN_SECRET_KEY:1KVXgaFPuijBxjvdRnHXBIw3TBOp8jtp}
  refresh_token_secret_key: ${REFRESH_TOKEN_SECRET_KEY:G7kPqX3tZmHcRV9LfWb0AsjNuDYx8TeQ}
  access_token_expire: ${ACCESS_TOKEN_EXPIRE:3600000}
  refresh_token_expire: ${REFRESH_TOKEN_EXPIRE:2592000000}

redis:
  cache:
    host: ${REDIS_CACHE_HOST:localhost}
    port: ${REDIS_CACHE_PORT:6380}
  queue:
    host: ${REDIS_QUEUE_HOST:localhost}
    port: ${REDIS_QUEUE_PORT:6381}

kafka:
  producer:
    default-option:
      linger-ms: 3000
      batch-size: 65536
    low-latency:
      linger-ms: 0
      batch-size: 16384

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

springdoc:
  cache:
    disabled: true
