spring:
  application:
    name: api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: ${DB_SHOW_SQL:false}
    hibernate:
      ddl-auto: none
