spring:
  application:
    name: seller-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        order_updates: true

        jdbc:
          batch_size: 100

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 5
      batch-size: 16384
    properties:
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
      linger.ms: 0
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8083}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
