server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/test_db?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999}
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  access_token_secret_key: ${ACCESS_TOKEN_SECRET_KEY:1KVXgaFPuijBxjvdRnHXBIw3TBOp8jtp}
  refresh_token_secret_key: ${REFRESH_TOKEN_SECRET_KEY:G7kPqX3tZmHcRV9LfWb0AsjNuDYx8TeQ}
  access_token_expire: ${ACCESS_TOKEN_EXPIRE:3600000}
  refresh_token_expire: ${REFRESH_TOKEN_EXPIRE:2592000000}

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

springdoc:
  cache:
    disabled: true
